In [26]:
# importing numpy library
import numpy as np


In [27]:
# 1. create a numpy array
arr = np.array([10,20,30,40,50])
print(f"Array: {arr}")

Array: [10 20 30 40 50]


In [28]:
# 2. Performing: Mean, max, min and sum.
print(f"Mean: {np.mean(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Min: {np.min(arr)}")
print(f"Sum: {np.sum(arr)}")

Mean: 30.0
Max: 50
Min: 10
Sum: 150


In [29]:
# 3. Create two arrays for arithmetic operations
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

print(f"Array 1 is {arr_1} and Array 2 is {arr_2}")
print(f"Addition: {arr_1 + arr_2}")
print(f"Multiplication: {arr_1 * arr_2}")

Array 1 is [1 2 3] and Array 2 is [4 5 6]
Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [ ]:
# 4. Create a 3x3 matrix

# Create a 3x3 matrix containing numbers from 1 to 9
matrix = matrix_3x3 = np.arange(1, 10).reshape(3, 3)

print(f"3x3 Matrix: '\n {matrix}")

3x3 Matrix: '
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
